config/routes.rb
Rails.application.routes.draw do
  resources :robots

  root 'robots#index'

end

app/models/robot.rb
class Robot < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/robots_controller.rb
class RobotsController < ApplicationController
  before_action :set_robot, only: [:show, :edit, :update, :destroy]
  include RobotsHelper
  # GET /robots
  # GET /robots.json
  def index
    @robots = Robot.all
    redirect_to new_robot_path if @robots.empty?
  end

  # GET /robots/1
  # GET /robots/1.json
  def show
  end

  # GET /robots/new
  def new
    @robot = Robot.new
  end

  # GET /robots/1/edit
  def edit
  end

  # POST /robots
  # POST /robots.json
  def create
    @robot = Robot.new(robot_params)

    report_exists = transform_command_to_movement(@robot, params[:command])    
    respond_to do |format|
      if @robot.save
        format.html { 
          flash[:notice] = 'Robot was successfully created.'
          select_route(report_exists)
        }
        format.json { render :show, status: :created, location: @robot }
      else
        format.html { render :new }
        format.json { render json: @robot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /robots/1
  # PATCH/PUT /robots/1.json
  def update
    report_exists = transform_command_to_movement(@robot, params[:command])
    respond_to do |format|
      if @robot.update(robot_params)
        format.html { 
          flash[:notice] = 'Robot was successfully updated.' 
          select_route(report_exists)
        }
        format.json { render :show, status: :ok, location: @robot }
      else
        format.html { render :edit }
        format.json { render json: @robot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /robots/1
  # DELETE /robots/1.json
  def destroy
    @robot.destroy
    respond_to do |format|
      format.html { redirect_to robots_url, notice: 'Robot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_robot
      @robot = Robot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def robot_params
      params[:robot].permit(:name, :x_coordinate, :y_coordinate, :position, :command)
    end

    def select_route(report)
      if report
        redirect_to robot_path(@robot)
      else 
        redirect_to edit_robot_path(@robot)
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/robots_helper.rb
module RobotsHelper

	def transform_command_to_movement(robot,command)
		command = command.upcase

		command = command.gsub(/ , /, ',')
		command = command.gsub(/, /, ',')
		command = command.gsub(/ ,/, ',')
		command = command.gsub(/PLACE /, 'PLACE_')

		# All the commands are split here
		command_array = command.split

		logger.info "command array: #{command_array}"

		for element in command_array
			should_update_robot = true

			case element
			when "MOVE"
				set_move(robot)
			when "LEFT" 
				set_left(robot)
			when "RIGHT"
				set_right(robot)
			when "REPORT"
				return true
			else
				if element.include? "PLACE"
					set_place(robot, element)
				end
				should_update_robot = false
			end		
				
			update_robot(robot) if should_update_robot
		end
		false
	end

	def update_robot(robot)
		unless robot.position.nil?
			robot.update_attributes(position: robot.position, x_coordinate: robot.x_coordinate, y_coordinate: robot.y_coordinate)
		end
	end

	def set_arrays
		Array @direction_array = Array.new
		Array @position_array = Array.new
		@direction_array = ["NORTH","EAST","SOUTH","WEST"]
		@position_array = [0,90,180,270]
	end

	def set_place (robot, string)
		set_arrays

		string_array = string[6..-1].split(',')		

		logger.info "string_array: #{string_array}"

		x = string_array.at(0)
		y = string_array.at(1)

		if (x.to_i < 6 && x.to_i > -1) && (y.to_i < 6 && y.to_i > -1)
			robot.x_coordinate = string_array.at(0)
			robot.y_coordinate = string_array.at(1)

			index = @direction_array.index(string_array.at(2))

			robot.position = @position_array.at(index)
			robot.update_attributes(position: robot.position, x_coordinate: robot.x_coordinate, y_coordinate: robot.y_coordinate)
		end
	end

	def set_left (robot)
		robot.position == 0 ? robot.position = 270 : robot.position -= 90
	end

	def set_right (robot)
		robot.position == 270 ? robot.position = 0 : robot.position += 90
	end

	def set_move (robot)
		case robot.position
		when 0
			robot.y_coordinate += 1 if robot.y_coordinate < 5
		when 90
			robot.x_coordinate += 1 if robot.x_coordinate < 5
		when 180
			robot.y_coordinate -= 1 if robot.y_coordinate > 0
		when 270
			robot.x_coordinate -= 1 if robot.x_coordinate > 0
		end
	end

	def get_report(robot)
		unless robot.position.nil?
			set_arrays
			index = @position_array.index(robot.position)
			report = "#{robot.x_coordinate},#{robot.y_coordinate},#{@direction_array.at(index)}"
		else
			report = "Robot #{robot.name} is not placed on the table yet."
		end
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RobotTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<br/>	
	<div class="container-fluid">
		<% unless notice.nil? %>
			<div class="alert alert-success">
				<%= notice %>
			</div>
		<% end %>
		<%= yield %>
	</div>
</body>
</html>

app/views/robots/_form.html.erb
<%= form_for(@robot) do |f| %>
  <% if @robot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@robot.errors.count, "error") %> prohibited this robot from being saved:</h2>

      <ul>
      <% @robot.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_for @robot do |f| %>
  <div class="form-group">
    <%= f.label "Name:" %>
    <%= f.text_field :name, class: "form-control" %>    
  </div>
  
  <div class="form-group">
    <%= f.label "Command for Robot:" %>
    <%= text_field_tag :command, nil, placeholder: 'example: PLACE 0,0,NORTH MOVE LEFT RIGHT REPORT', class: 'form-control' %>  
  </div>

  <div class="form-group">
    <div class="btn-group" role="button">
      <%= f.submit "Play Robot", class: "btn btn-info" %>
  </div>
  <% end %>
<% end %>

app/views/robots/edit.html.erb
<h1>Editing Robot</h1>

<%= render 'form' %>

<%= link_to 'Show', @robot %> |
<%= link_to 'Back', robots_path %>

app/views/robots/index.html.erb
<h1>Listing Robots</h1>

<div class="text-center">
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th style="text-align:center">Name</th>
        <th style="text-align:center">Current Position</th>
      </tr>
    </thead>

    <tbody>
      <% @robots.each do |robot| %>
        <tr>
          <td><%= robot.name %></td>
          <td><%= get_report(robot) %></td>
          <td><%= link_to 'Show', robot %></td>
          <td><%= link_to 'Edit', edit_robot_path(robot) %></td>
          <td><%= link_to 'Destroy', robot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>

<%= link_to 'New Robot', new_robot_path %>

app/views/robots/new.html.erb
<h1>New Robot</h1>

<%= render 'form' %>

<%= link_to 'Back', robots_path %>

app/views/robots/show.html.erb
<h1>Show Robot <%= @robot.id %></h1>

Name: <%= @robot.name %>
<br/>
Report: <%= get_report(@robot) %>
<br/>

<%= link_to 'Edit', edit_robot_path(@robot) %> |
<%= link_to 'Back', robots_path %>